name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [26.x]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v6
      with:
         version: 12
         cache: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: make install

    - name: Launch Unit tests
      run: make test
